// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMoUny2ASVauBd9Vy-UM7jIMkVU4YUR0',
    appId: '1:21091457285:web:6b6624fbb239b767c63f6c',
    messagingSenderId: '21091457285',
    projectId: 'skill-chain',
    authDomain: 'skill-chain.firebaseapp.com',
    storageBucket: 'skill-chain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADVUZ9MmHJerZUtFdDss5kv9-0JJFg45g',
    appId: '1:21091457285:android:f6cb9c4bed1cf400c63f6c',
    messagingSenderId: '21091457285',
    projectId: 'skill-chain',
    storageBucket: 'skill-chain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0DpPl0YbQ0yUlqw5HRHgpCdajFPB6d8',
    appId: '1:21091457285:ios:ee0f0744c0dc57d9c63f6c',
    messagingSenderId: '21091457285',
    projectId: 'skill-chain',
    storageBucket: 'skill-chain.appspot.com',
    iosBundleId: 'com.skill.chain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0DpPl0YbQ0yUlqw5HRHgpCdajFPB6d8',
    appId: '1:21091457285:ios:1e028710cbf31762c63f6c',
    messagingSenderId: '21091457285',
    projectId: 'skill-chain',
    storageBucket: 'skill-chain.appspot.com',
    iosBundleId: 'com.example.skillChain.RunnerTests',
  );
}
